<?php
if( ! defined('__ANUBISTHEJACKLE_UNIT_TEST_BOOTSTRAP_LOADED') ){
    define('__ANUBISTHEJACKLE_UNIT_TEST_BOOTSTRAP_LOADED', true);
}else{
    define('__ANUBISTHEJACKLE_UNIT_TEST_BOOTSTRAP_LOADED_TWICE', true);
}